import { PRODUCTS, resolveProductUrls, type ProductUrls } from "@centerfuse/config";
import { renderDocument, renderFamilyFooter, renderFamilyHeader, renderState } from "@centerfuse/ui";

export function renderBuyFuseDashboard(urls: ProductUrls = resolveProductUrls({})): string {
  const body = `${renderFamilyHeader("BUYFUSE", urls)}<main id="main" class="shell">
  <section class="hero"><p class="eyebrow">Your buyer workspace</p><h1 class="display">Remember what caught your eye.</h1><p class="lede">Keep product links and personal notes together while you decide what is right for you.</p></section>
  <section id="auth" class="card"><h2>Open your workspace</h2><p>Use your CenterFuse identity foundation to keep your BuyFuse items private.</p><div class="grid"><label class="field">Email<input id="email" type="email" autocomplete="email"></label><label class="field">Password<input id="password" type="password" minlength="12" autocomplete="current-password"></label></div><div class="row"><button id="login">Sign in</button><button class="button secondary" id="register">Create account</button></div></section>
  <section id="workspace" class="stack" hidden><div class="grid"><article class="card"><p class="eyebrow">Saved</p><strong id="saved-count" class="display" style="font-size:3rem">0</strong><p>items in your workspace</p></article><article class="card"><p class="eyebrow">A quieter decision space</p><h2>Keep context close.</h2><p>Add what matters to you without rebuilding a seller listing.</p></article></div>
  <section class="card"><h2>Save an item</h2><form id="save-form" class="stack"><label class="field">Item name<input id="title" required minlength="2" maxlength="200"></label><label class="field">Source link (optional)<input id="source-url" type="url" placeholder="https://"></label><label class="field">Notes (optional)<textarea id="notes" maxlength="2000" placeholder="Size, color, delivery details, questions…"></textarea></label><button>Save to BuyFuse</button></form></section>
  <section class="card"><h2>Your items</h2><div id="items">${renderState("empty", "Nothing saved yet", "Add an item above and it will appear here.")}</div></section></section>
  <p id="status" class="toast" role="status" aria-live="polite" hidden></p></main>${renderFamilyFooter(urls)}`;
  const scripts = `const tokenKey='buyfuseToken';let token=sessionStorage.getItem(tokenKey)||'';const el=id=>document.getElementById(id);function say(message){const node=el('status');node.textContent=message;node.hidden=false;setTimeout(()=>node.hidden=true,3500)}async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({error:'INVALID_RESPONSE'}));if(!response.ok)throw new Error(data.error||'REQUEST_FAILED');return data}async function authenticate(mode){try{const data=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify({email:el('email').value,password:el('password').value})});token=data.accessToken;sessionStorage.setItem(tokenKey,token);await load();say('Your workspace is ready.')}catch(error){say('Could not continue: '+error.message)}}function safe(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function load(){const data=await api('/api/workspace');el('auth').hidden=true;el('workspace').hidden=false;el('saved-count').textContent=data.savedItems.length;el('items').innerHTML=data.savedItems.length?data.savedItems.map(item=>'<article class="state" style="text-align:left"><h3>'+safe(item.title)+'</h3>'+(item.sourceUrl?'<p><a target="_blank" rel="noopener" href="'+safe(item.sourceUrl)+'">Open source</a></p>':'')+'<p>'+safe(item.notes||'No notes yet.')+'</p><label class="field">Status<select data-item="'+item.id+'"><option '+(item.status==='CONSIDERING'?'selected':'')+'>CONSIDERING</option><option '+(item.status==='PURCHASED'?'selected':'')+'>PURCHASED</option><option '+(item.status==='ARCHIVED'?'selected':'')+'>ARCHIVED</option></select></label></article>').join(''):'<section class="state empty" role="status"><h2>Nothing saved yet</h2><p>Add an item above and it will appear here.</p></section>';document.querySelectorAll('[data-item]').forEach(select=>select.onchange=async()=>{try{await api('/api/items/'+select.dataset.item+'/status',{method:'PATCH',body:JSON.stringify({status:select.value})});say('Status updated.')}catch(error){say(error.message)}})}el('login').onclick=()=>authenticate('login');el('register').onclick=()=>authenticate('register');el('save-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/items',{method:'POST',body:JSON.stringify({title:el('title').value,sourceUrl:el('source-url').value||undefined,notes:el('notes').value||undefined})});event.target.reset();await load();say('Item saved.')}catch(error){say('Could not save: '+error.message)}};if(token)load().catch(()=>{token='';sessionStorage.removeItem(tokenKey)});`;
  return renderDocument({ product: PRODUCTS.BUYFUSE, title: "BuyFuse — Your buyer workspace", description: "Keep items you are considering, source links, and notes organized in BuyFuse.", body, scripts });
}

export function renderBuyFuseState(kind: "loading" | "error" | "not-found", urls: ProductUrls = resolveProductUrls({})): string { const state = kind === "loading" ? renderState("loading", "Loading BuyFuse", "Opening your workspace…") : kind === "error" ? renderState("error", "Workspace unavailable", "BuyFuse could not complete that request.") : renderState("empty", "Page not found", "That BuyFuse page does not exist."); return renderDocument({ product: PRODUCTS.BUYFUSE, title: "BuyFuse", description: "BuyFuse status", body: `${renderFamilyHeader("BUYFUSE", urls)}<main id="main" class="shell hero">${state}</main>${renderFamilyFooter(urls)}` }); }
