import { PRODUCTS, resolveProductUrls, type ProductUrls } from "@centerfuse/config";
import { familyStyles, renderFamilyFooter, renderFamilyHeader } from "@centerfuse/ui";

export function renderAppPage(apiUrl: string, urls: ProductUrls = resolveProductUrls({})): string {
  const safeApiUrl = JSON.stringify(apiUrl.replace(/\/$/, "")).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SellFuse — List once. Sell everywhere.</title>
<style>
${familyStyles(PRODUCTS.SELLFUSE)}
:root{font-family:Inter,ui-sans-serif,system-ui;color:#173126;background:#f4f1e9}*{box-sizing:border-box}body{margin:0}main{max-width:960px;margin:auto;padding:48px 20px 96px}header{margin-bottom:36px}.eyebrow{color:#d9512d;font-weight:800;letter-spacing:.08em;text-transform:uppercase}h1{font-size:clamp(2.6rem,8vw,5.8rem);line-height:.93;margin:.2em 0}h2{margin-top:0}.lede{font-size:1.2rem;max-width:650px;line-height:1.6}.card{background:#fff;border:1px solid #d8ddd8;border-radius:22px;padding:24px;margin:18px 0;box-shadow:0 8px 30px #1731260d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}label{display:grid;gap:7px;font-weight:700}input,textarea,select{width:100%;padding:12px;border:1px solid #aebbb4;border-radius:10px;font:inherit}textarea{min-height:110px}button{border:0;border-radius:999px;padding:12px 19px;background:#173f2d;color:#fff;font-weight:800;cursor:pointer}button.secondary{background:#e9eee9;color:#173126}button:disabled{opacity:.5;cursor:wait}.marketplaces{display:flex;flex-wrap:wrap;gap:9px}.marketplaces label{display:flex;background:#eef1ed;border-radius:999px;padding:9px 13px;font-weight:600}.marketplaces input{width:auto}.steps{display:flex;gap:7px;overflow:auto;padding:4px 0 18px}.step{white-space:nowrap;background:#e5eae5;border-radius:999px;padding:7px 11px;font-size:.82rem}.price{font-size:2.5rem;font-weight:900}.muted{color:#5e6d65}.warning{background:#fff2dd;border-color:#efc879}.success{background:#e7f5e9;border-color:#9bc7a0}.evidence{border-left:4px solid #d9512d;padding-left:14px;margin:13px 0}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}pre{white-space:pre-wrap;background:#f5f7f4;padding:12px;border-radius:10px}.hidden{display:none}.status{min-height:24px;font-weight:700}
</style></head><body>${renderFamilyHeader("SELLFUSE", urls)}<main id="main">
<header><div class="eyebrow">AI selling assistant for ordinary people</div><h1>Take pictures.<br>Sell with confidence.</h1><p class="lede">SellFuse identifies the item, separates market evidence from AI reasoning, prepares each marketplace draft, and leaves the final call with you.</p></header>
<div class="steps"><span class="step">1 Photos</span><span class="step">2 Identify</span><span class="step">3 Value</span><span class="step">4 Prepare</span><span class="step">5 Review</span><span class="step">6 Publish</span><span class="step">7 Mark sold</span></div>
<section id="auth" class="card"><h2>Start securely</h2><p class="muted">Create a SellFuse account or sign in. Your private AI gateway token never reaches this page.</p><div class="grid"><label>Email<input id="email" type="email" autocomplete="email"></label><label>Password<input id="password" type="password" minlength="12" autocomplete="current-password"></label></div><div class="actions"><button id="login">Sign in</button><button id="register" class="secondary">Create account</button></div></section>
<section id="capture" class="card hidden"><h2>What are you selling?</h2><label>Photos<input id="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label>What you already know (optional)<textarea id="notes" placeholder="It powers on; I bought it in 2022; the charger is included..."></textarea></label><h3>Where might you sell it?</h3><div id="marketplaces" class="marketplaces"></div><div class="actions"><button id="prepare">Identify and prepare</button></div></section>
<div id="status" class="status" role="status" aria-live="polite"></div><section id="result" class="hidden"></section>
</main>${renderFamilyFooter(urls)}<script>
const API=${safeApiUrl}; const marketplaceNames={EBAY:'eBay',PINTEREST:'Pinterest',FACEBOOK_MARKETPLACE:'Facebook Marketplace',INSTAGRAM:'Instagram',OFFERUP:'OfferUp',MERCARI:'Mercari',POSHMARK:'Poshmark',DEPOP:'Depop',CRAIGSLIST:'Craigslist'};
let token=sessionStorage.getItem('sellfuseToken')||''; let current=null; let listingId='';
const byId=(id)=>document.getElementById(id); const status=(message)=>byId('status').textContent=message;
async function api(path,options={}){if(!API)throw new Error('SellFuse API is not connected to this deployment.');const response=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({error:'INVALID_RESPONSE'}));if(!response.ok)throw new Error(data.error||'REQUEST_FAILED');return data}
async function authenticate(mode){try{status(mode==='register'?'Creating account…':'Signing in…');const data=await api('/v1/auth/'+mode,{method:'POST',body:JSON.stringify({email:byId('email').value,password:byId('password').value})});token=data.accessToken;sessionStorage.setItem('sellfuseToken',token);showCapture();status('Ready for photos.')}catch(error){status('Could not continue: '+error.message)}}
async function showCapture(){try{const capabilities=await api('/v1/marketplaces/capabilities');byId('marketplaces').innerHTML=capabilities.map((cap)=>'<label><input type="checkbox" value="'+cap.marketplace+'">'+marketplaceNames[cap.marketplace]+' · '+(cap.implementationStatus==='AVAILABLE'?'Assisted':'Planned')+'</label>').join('');byId('auth').classList.add('hidden');byId('capture').classList.remove('hidden')}catch{token='';sessionStorage.removeItem('sellfuseToken')}}
function selectedMarkets(){return [...document.querySelectorAll('#marketplaces input:checked')].map((input)=>input.value)}
async function imageInput(file){const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});return {mimeType:file.type,base64:data,name:file.name}}
async function prepare(){const button=byId('prepare');try{button.disabled=true;status('Looking closely at your photos…');const photos=await Promise.all([...byId('photos').files].map(imageInput));current=await api('/v1/intelligence/prepare',{method:'POST',body:JSON.stringify({photos,sellerNotes:byId('notes').value,marketplaces:selectedMarkets()})});renderResult(current);status(current.mode==='AI_ASSISTED'?'Ready for your review.':'AI is unavailable—continue manually below.')}catch(error){status('Could not prepare this item: '+error.message)}finally{button.disabled=false}}
function money(value,currency='USD'){return value==null?'No evidence-backed price':new Intl.NumberFormat(undefined,{style:'currency',currency}).format(value)}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]))}
function renderResult(data){const analysis=data.analysis;const value=data.valuation;const master=data.masterListing||{title:'',category:'',description:'',suggestedPrice:null};byId('result').innerHTML='<section class="card"><div class="eyebrow">Identification</div><h2>'+escapeHtml(analysis.likelyItem)+'</h2><p>Confidence: '+Math.round(analysis.confidence*100)+'%</p><p>'+escapeHtml(analysis.condition||'Condition needs your review')+'</p><p class="muted">Still needed: '+escapeHtml(analysis.missingInformation.join('; ')||'Nothing flagged')+'</p></section><section class="card '+(value.recommendedAsk==null?'warning':'')+'"><div class="eyebrow">Value</div><div class="price">'+money(value.recommendedAsk,value.currency)+'</div><p>Quick sale: '+money(value.quickSalePrice,value.currency)+' · High ask: '+money(value.highAskPrice,value.currency)+'</p><p>'+escapeHtml(value.reasoning)+'</p>'+value.evidence.map((item)=>'<div class="evidence"><strong>'+escapeHtml(item.type.replaceAll('_',' '))+'</strong> · '+escapeHtml(item.sourceName)+(item.price!=null?' · '+money(item.price,item.currency):'')+(item.sourceUrl?' · <a target="_blank" rel="noopener" href="'+escapeHtml(item.sourceUrl)+'">View source</a>':'')+'</div>').join('')+'<p class="muted">'+escapeHtml(value.limitations.join(' '))+'</p></section><section class="card"><div class="eyebrow">Your master listing</div><div class="grid"><label>Title<input id="reviewTitle" value="'+escapeHtml(master.title)+'"></label><label>Category<input id="reviewCategory" value="'+escapeHtml(master.category)+'"></label><label>Price<input id="reviewPrice" type="number" min="0" step="0.01" value="'+escapeHtml(master.suggestedPrice??'')+'"></label></div><label>Description<textarea id="reviewDescription">'+escapeHtml(master.description)+'</textarea></label><div class="actions"><button id="publish">Approve and prepare publishing</button></div></section>';byId('result').classList.remove('hidden');byId('publish').onclick=publish}
async function publish(){try{const markets=selectedMarkets();const price=Number(byId('reviewPrice').value);if(!markets.length)throw new Error('Choose at least one marketplace');if(!Number.isFinite(price)||price<=0)throw new Error('Enter the price you want to ask');status('Saving your reviewed listing…');if(!current.masterListing){current=await api('/v1/intelligence/manual',{method:'POST',body:JSON.stringify({title:byId('reviewTitle').value,category:byId('reviewCategory').value,description:byId('reviewDescription').value,price,marketplaces:markets})})}const master={...current.masterListing,title:byId('reviewTitle').value,category:byId('reviewCategory').value,description:byId('reviewDescription').value,suggestedPrice:price};const created=await api('/v1/listings',{method:'POST',body:JSON.stringify({masterListing:master,marketplaces:markets})});listingId=created.id;await api('/v1/listings/'+listingId+'/review',{method:'POST',body:JSON.stringify(master)});const published=await api('/v1/listings/'+listingId+'/publish',{method:'POST',body:'{}'});renderPublish(published);status('Drafts prepared. Complete any assisted handoffs, then mark sold once here.')}catch(error){status('Could not publish: '+error.message)}}
function renderPublish(listing){byId('result').insertAdjacentHTML('beforeend','<section class="card success"><h2>Marketplace handoffs</h2>'+listing.publishResults.map((item)=>'<p><strong>'+marketplaceNames[item.marketplace]+'</strong> · '+item.status+(item.handoffUrl?' · <a target="_blank" rel="noopener" href="'+escapeHtml(item.handoffUrl)+'">Open marketplace</a>':'')+'</p>').join('')+'<label>Sold on<select id="soldOn">'+listing.drafts.map((draft)=>'<option value="'+draft.marketplace+'">'+marketplaceNames[draft.marketplace]+'</option>').join('')+'</select></label><div class="actions"><button id="sold">Mark sold once</button></div></section>');byId('sold').onclick=markSold}
async function markSold(){try{const sold=await api('/v1/listings/'+listingId+'/sold',{method:'POST',body:JSON.stringify({soldOn:byId('soldOn').value})});status('Marked sold in SellFuse. '+sold.soldActions.length+' marketplace follow-up actions are ready.');byId('sold').disabled=true}catch(error){status('Could not mark sold: '+error.message)}}
byId('login').onclick=()=>authenticate('login');byId('register').onclick=()=>authenticate('register');byId('prepare').onclick=prepare;if(!API)status('The SellFuse UI is live; connect its protected API deployment to enable seller workflows.');else if(token)showCapture();
</script></body></html>`;
}
